# Generated by Django 6.0.7 on 2026-08-03 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(help_text='Example: House 15, Green Valley Apartments', max_length=150)),
                ('street', models.CharField(help_text='Example: Ngong Road', max_length=100)),
                ('county', models.CharField(help_text='Example: Nairobi', max_length=100)),
                ('postal_code', models.CharField(help_text='00100', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Customer Profiles',
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_email', models.EmailField(max_length=254, unique=True)),
                ('business_address', models.CharField(help_text='Example: Stall 24, Greenspan Mall', max_length=150)),
                ('phone_number', models.CharField(help_text='0712345678', max_length=10)),
                ('description', models.TextField()),
                ('street', models.CharField(help_text='Example: Ngong Road', max_length=100)),
                ('county', models.CharField(help_text='Example: Nairobi', max_length=100)),
                ('postal_code', models.CharField(help_text='00100', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJEECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sellers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Seller Profiles',
            },
        ),
    ]
