# Generated by Django 6.0.7 on 2026-08-11 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='county',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='street',
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Example: Home, Work, Office', max_length=50)),
                ('shipping_address', models.CharField(help_text='Example: House 15, Green Valley Apartments', max_length=150)),
                ('street', models.CharField(help_text='Example: Ngong Road', max_length=100)),
                ('county', models.CharField(help_text='Example: Nairobi', max_length=100)),
                ('postal_code', models.CharField(help_text='00100', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text="Marks this as the customer's default shipping address")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_addresses', to='accounts.customerprofile')),
            ],
            options={
                'db_table': 'Customer Address',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
