# Generated by Django 6.0.7 on 2026-09-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customerprofile_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='phone_number',
            field=models.CharField(help_text='0712345678', max_length=10, unique=True),
        ),
    ]
