# Generated by Django 6.0.7 on 2026-09-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_sellerprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='phone_number',
        ),
    ]
