# Generated by Django 5.1.3 on 2025-01-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
