# Generated by Django 5.1.3 on 2025-01-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='item_name',
            new_name='item_type',
        ),
    ]
